
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # Uncomment this if you want to bring up
  # the  machines with a GUI
  #config.vm.provider "virtualbox" do |v|
  #  v.gui = true
  #end



  config.vm.define "controller" do |controller|
    controller.vm.hostname = "controller"
    controller.vm.box = "ubuntu/bionic64"
    # This configuration assumes that we have already created two hostonly 
    # If this has not been done, please run the script ../scripts/createVBoxNetworks.sh
    controller.vm.network "private_network", ip: "192.168.1.11", name: 'vboxnet0'
    controller.vm.network "forwarded_port", guest: 22, host: 8222
    controller.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.memory = 6144
      v.cpus = 2
    end
  end

  config.vm.define "network" do |network|
    # This configuration assumes that we have already created two hostonly 
    # If this has not been done, please run the script ../scripts/createVBoxNetworks.sh
    network.vm.hostname = "network"
    network.vm.box = "ubuntu/bionic64"
    network.vm.network "private_network", ip: "192.168.1.12", name: 'vboxnet0'
    network.vm.network "private_network", ip: "192.168.2.12",  name: 'vboxnet2'
    network.vm.network "forwarded_port", guest: 22, host: 8223
    network.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      v.memory = 4096
      v.cpus = 2
    end
  end

  config.vm.define "compute1" do |compute1|
    compute1.vm.hostname = "compute1"
    compute1.vm.box = "ubuntu/bionic64"
    compute1.vm.network "private_network", ip: "192.168.1.21", name: 'vboxnet0'
    compute1.vm.network "private_network", ip: "192.168.2.21",  name: 'vboxnet2'
    compute1.vm.network "forwarded_port", guest: 22, host: 8200
    compute1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      v.memory = 4096
      v.cpus = 2
    end
  end

  config.vm.define "compute2" do |compute2|
    compute2.vm.hostname = "compute2"
    compute2.vm.box = "ubuntu/bionic64"
    compute2.vm.network "private_network", ip: "192.168.1.22", name: 'vboxnet0'
    compute2.vm.network "private_network", ip: "192.168.2.22",  name: 'vboxnet2'
    compute2.vm.network "forwarded_port", guest: 22, host: 8201
    compute2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      v.memory = 4096
      v.cpus = 2
    end
  end


end
