---
# On each node, we create files which we can easily source from the shell
# to set the OS_* environment variables expected by the openstack client
# The first one - admin_openrc - corresponds to the admin role, the second
# one to our demo user
- name: Create admin-openrc
  template:
    dest: "{{install_user_home}}/admin-openrc"
    force: yes
    mode: 0700
    src: "admin_openrc.j2"
- name: Create demo-openrc
  template:
    dest: "{{install_user_home}}/demo-openrc"
    force: yes
    mode: 0700
    src: "demo_openrc.j2"
- name: Distribute private key
  copy:
    src: "{{playbook_dir}}/demo-key"
    dest: "{{install_user_home}}/demo-key"
    owner: "{{install_user}}"
    group: "{{install_user}}"
    mode: 0700
- name: Distribute public key
  copy:
    src: "{{playbook_dir}}/demo-key.pub"
    dest: "{{install_user_home}}/demo-key.pub"
    owner: "{{install_user}}"
    group: "{{install_user}}"
    mode: 0700
