---
- name: Install NGINX 
  apt:
    force_apt_get: yes
    update_cache: yes
    name: nginx 
    state: latest 
- name: Create configuration file 
  template:
    src: proxy.conf.j2 
    dest: /etc/nginx/conf.d/proxy.conf 
    owner: root 
    group: root
    mode: 0644 
- name: Make sure that etc/nginx/certs exists 
  file: 
    state: directory
    path: "/etc/nginx/certs"
- name: Copy certificates for NGINX
  copy:
    src: "{{credentials_dir}}/nginx/{{item}}"
    dest: "/etc/nginx/certs/{{item}}"
  loop:
    - server.crt 
    - server.rsa
- name: Restart service 
  service:
    name: nginx 
    state: restarted
  
