---
# First we create the credentials. If there is already a file with the
# credentials in place, we leave it alone as the credentials therein
# are most likely already in use
- name: Check if credentials.yaml exists
  stat:
    path: "{{playbook_dir}}/credentials.yaml"
  register: credentials_yaml
- name: Create secure MariaDB password
  shell:
    pwgen -1
  register: pwgen_mariadb
  when: credentials_yaml.stat.exists == False
- name: Create secure OS password
  shell:
    pwgen -1
  register: pwgen_os
  when: credentials_yaml.stat.exists == False
- name: Create shared secrent for metadata agent
  shell:
    pwgen -1 50
  register: pwgen_metadata
  when: credentials_yaml.stat.exists == False
- name: Create secure demo user password
  shell:
    pwgen -1
  register: pwgen_demo
  when: credentials_yaml.stat.exists == False
- name: Create credentials
  template:
    dest: "{{playbook_dir}}/credentials.yaml"
    force: no
    src: "credentials.yaml.j2"
  when: credentials_yaml.stat.exists == False

# Now we create an SSH key pair and place it in the
# playbook directory
- name: Create key pair locally
  openssh_keypair:
    path: "{{playbook_dir}}/{{ssh_key_name}}"
    size: 2048
    type: rsa
    state: present
