galaxy_info:
  author: christianb93
  description: Install Neutron agents (OVS agent, DHCP agent, Metadata agent) on a node
  license: MIT
  min_ansible_version: 2.4
  galaxy_tags: []
dependencies: ["ovs_agent"]
