
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # Uncomment this if you want to bring up
  # the  machines with a GUI
  #config.vm.provider "virtualbox" do |v|
  #  v.gui = true
  #end


  config.vm.define "controller" do |controller|
    controller.vm.hostname = "controller"
    controller.vm.box = "ubuntu/bionic64"
    controller.vm.network "private_network", ip: "192.168.1.11", virtualbox__intnet: "managementNetwork"
    controller.vm.network "private_network", ip: "172.0.0.1",  auto_config: false, name: 'vboxnet0'
    controller.vm.network "forwarded_port", guest: 22, host: 8222
    controller.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      v.memory = 6144
      v.cpus = 2
    end
  end




end
