
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|


 
  config.vm.define "box" do |box|
    box.vm.hostname = "box"
    box.vm.box = "ubuntu/bionic64"
    box.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      # Create and attach two additional disks with 5 GB each. If this fails, check whether the HDD already exists with 
      # vboxmanage list hdds 
      # and if yes, remove it using vboxmanage closemedium UUID and also delete the files vhd*.img
      # We use port 2 and 3 of the existing SCSI controller as adding an SATA controller will 
      # cause issues with the boot order
      # These disks will be visible as /dev/sdc  and /dev/sdd inside the machine
      v.customize ["createhd", "disk", "--filename", "./vhd1.img", "--size", 5 * 1024]
      v.customize ["createhd", "disk", "--filename", "./vhd2.img", "--size", 5 * 1024]
      v.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 2, "--device", 0, "--type", "hdd", "--medium", "./vhd1.img"]
      v.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 3, "--device", 0, "--type", "hdd", "--medium", "./vhd2.img"]
      v.memory = 2048
      v.cpus = 2
    end
  end


end
