#
# Create credentials
#
- name: Create credentials
  hosts: localhost
  vars_files:
    - global_vars.yaml
  roles:
    - prepareCredentials


#
# Now import the credentials just created. We cannot
# include this in vars_files as the file is not yet
# present when we run the playbook.
#
- name: Import credentials
  hosts: all
  gather_facts: no
  vars_files:
    global_vars.yaml
  tasks:
    - name: Read credentials
      include_vars:
        file: "{{credentials_dir}}/credentials.yaml"

# Make sure that all hosts are up before proceeding
- name: Check connectivity
  hosts: all
  tasks:
    - name: Check connectivity
      ping:


#
# Perform basic setup steps on all nodes. This will
# - distribute credentials
# - set up networking
# - register the Cloud APT repository
# - install the python3 openstack client
#
- name: Basic node setup
  hosts: all
  become: yes
  vars_files:
    - global_vars.yaml
    - "{{playbook_dir}}/../conf/apt_proxy.yaml"
  roles:
    - nodeSetup


#
# Set up the controller node as NTP server
#
- name: Install NTP on controller node
  hosts: controller_nodes
  become: yes
  vars_files:
    global_vars.yaml
  vars:
    ntp_network_cidr: "{{management_network_cidr}}"
  roles:
    - ntpServer

#
# Set up the compute nodes as NTP clients
#
- name: Install NTP client on compute nodes
  hosts: compute_nodes
  become: yes
  vars_files:
    global_vars.yaml
  vars:
    ntp_server_name: controller
  roles:
    - ntpClient


#
# Install MariaDB, Memcached and RabbitMQ on the controller
#
- name: Install middleware on controller node
  hosts: controller_nodes
  become: yes
  vars:
    mariadb_server_ip: "{{hostvars.controller.mgmt_ip}}"
    mariadb_root_password: "{{MARIADB_ROOT_PASSWORD}}"
    rabbit_user_name: "openstack"
    rabbit_user_password: "{{OS_SERVICE_PASSWORD}}"
    memcached_server_ip: "{{hostvars.controller.mgmt_ip}}"
  roles:
    - mariaDB
    - rabbitMQ
    - memcached


#
# Install Keystone on the controller node
#
- name: Install Keystone on controller node
  hosts: controller_nodes
  become: yes
  vars:
    mysql_server_name: controller
    keystone_db_user_password: "{{OS_ADMIN_PASSWORD}}"
  roles:
    - keystone
